"""
Auto-generated Pydantic schemas from SQLAlchemy models

Generated by: src/utils/codegen.py
DO NOT EDIT MANUALLY - Run `python -m src.utils.codegen generate` to regenerate

These schemas provide:
- Full IDE type hints and autocomplete
- Moose OLAP compatibility
- Pydantic validation
"""

from pydantic import BaseModel, Field
from datetime import datetime
from decimal import Decimal
from typing import Literal


# ==================== Base Schemas (OLTP) ====================

class Customer(BaseModel):
    """Generated from SQLAlchemy model: Customer"""
    id: int
    email: str = Field(max_length=255)
    name: str = Field(max_length=255)
    country: str = Field(max_length=100)
    city: str = Field(max_length=100)
    created_at: datetime


class Product(BaseModel):
    """Generated from SQLAlchemy model: Product"""
    id: int
    name: str = Field(max_length=255)
    category: str = Field(max_length=100)
    price: Decimal = Field(decimal_places=2)
    created_at: datetime


class Order(BaseModel):
    """Generated from SQLAlchemy model: Order"""
    id: int
    customer_id: int
    order_date: datetime
    status: str = Field(max_length=50)
    total: Decimal = Field(decimal_places=2)


class OrderItem(BaseModel):
    """Generated from SQLAlchemy model: OrderItem"""
    id: int
    order_id: int
    product_id: int
    quantity: int
    price: Decimal = Field(decimal_places=2)


# ==================== CDC Metadata ====================

class CdcMetadata(BaseModel):
    """Redpanda Connect CDC metadata"""
    table: str
    operation: Literal["delete", "insert", "update", "read"]
    lsn: str  # PostgreSQL LSN as hex string


class CdcFields(BaseModel):
    """ClickHouse CDC tracking fields"""
    is_deleted: int = Field(ge=0, le=1)  # UInt8
    lsn: int  # UInt64


# ==================== Dimension Tables (OLAP) ====================

class CustomerDimension(Customer, CdcFields):
    """OLAP dimension/fact for Customer with CDC tracking"""
    pass


class ProductDimension(Product, CdcFields):
    """OLAP dimension/fact for Product with CDC tracking"""
    pass


class OrderDimension(Order, CdcFields):
    """OLAP dimension/fact for Order with CDC tracking"""
    pass


class OrderItemFact(OrderItem, CdcFields):
    """OLAP dimension/fact for OrderItem with CDC tracking"""
    pass
