input:
  postgres_cdc:
    dsn: 'postgresql://postgres:postgres@sqlmodel-postgres:5432/sqlmodel_db?sslmode=disable'
    schema: 'public'
    slot_name: 'redpanda_cdc_slot'
    tables:
      - 'customer'
      - 'product'
      - 'order'
      - 'orderitem'

pipeline:
  processors:
    # Structure CDC event with metadata and payload fields
    - mapping: |
        root.metadata = {
          "table": meta("table"),
          "operation": meta("operation"),
          "lsn": meta("lsn")
        }
        root.payload = this

output:
  kafka:
    addresses:
      - 'redpanda:9092'
    topic: 'sqlmodel_cdc_events'
    max_in_flight: 1

http:
  address: '0.0.0.0:4195'
