# Redpanda Connect PostgreSQL CDC Configuration
#
# The postgres_cdc input automatically adds metadata to each message:
# - meta("table")     - table name where the change occurred
# - meta("operation") - operation type (read, insert, update, delete)
# - meta("lsn")       - PostgreSQL Log Sequence Number

input:
  postgres_cdc:
    dsn: '${POSTGRES_CDC_DSN:-postgres://postgres:postgres@${APP_NAME:-sqlmodel}-postgres:5432/${POSTGRES_DB:-sqlmodel_db}?sslmode=disable}'
    schema: ${POSTGRES_CDC_SCHEMA:-public}
    slot_name: ${POSTGRES_CDC_SLOT:-redpanda_cdc_slot}
    tables: ${POSTGRES_CDC_TABLES:-["customer","product","order","orderitem"]}

pipeline:
  processors:
    # Copy metadata into payload for easier access in Moose streaming functions
    - mapping: |
        root.metadata = {
          "table": meta("table"),
          "operation": meta("operation"),
          "lsn": meta("lsn")
        }
        root.payload = this

output:
  kafka:
    addresses:
      - 'redpanda:9092'
    topic: ${POSTGRES_CDC_TOPIC:-sqlmodel_cdc_events}
    max_in_flight: 1

http:
  address: '0.0.0.0:4195'
